package com.keqiaokeji.tezizai.common.dbmapper.uc.domain;

public class UcCorpInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_corp_info.corp_id
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private String corpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_corp_info.corp_code
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private String corpCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_corp_info.corp_name
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private String corpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_corp_info.status
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_corp_info.record_status
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private String recordStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_corp_info.create_user_id
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_corp_info.create_time
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_corp_info.last_modify_user_id
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private String lastModifyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_corp_info.last_modify_time
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private Long lastModifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_corp_info.corp_id
     *
     * @return the value of uc_corp_info.corp_id
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public String getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_corp_info.corp_id
     *
     * @param corpId the value for uc_corp_info.corp_id
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_corp_info.corp_code
     *
     * @return the value of uc_corp_info.corp_code
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public String getCorpCode() {
        return corpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_corp_info.corp_code
     *
     * @param corpCode the value for uc_corp_info.corp_code
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setCorpCode(String corpCode) {
        this.corpCode = corpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_corp_info.corp_name
     *
     * @return the value of uc_corp_info.corp_name
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public String getCorpName() {
        return corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_corp_info.corp_name
     *
     * @param corpName the value for uc_corp_info.corp_name
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setCorpName(String corpName) {
        this.corpName = corpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_corp_info.status
     *
     * @return the value of uc_corp_info.status
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_corp_info.status
     *
     * @param status the value for uc_corp_info.status
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_corp_info.record_status
     *
     * @return the value of uc_corp_info.record_status
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public String getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_corp_info.record_status
     *
     * @param recordStatus the value for uc_corp_info.record_status
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_corp_info.create_user_id
     *
     * @return the value of uc_corp_info.create_user_id
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_corp_info.create_user_id
     *
     * @param createUserId the value for uc_corp_info.create_user_id
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_corp_info.create_time
     *
     * @return the value of uc_corp_info.create_time
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_corp_info.create_time
     *
     * @param createTime the value for uc_corp_info.create_time
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_corp_info.last_modify_user_id
     *
     * @return the value of uc_corp_info.last_modify_user_id
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public String getLastModifyUserId() {
        return lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_corp_info.last_modify_user_id
     *
     * @param lastModifyUserId the value for uc_corp_info.last_modify_user_id
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setLastModifyUserId(String lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_corp_info.last_modify_time
     *
     * @return the value of uc_corp_info.last_modify_time
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public Long getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_corp_info.last_modify_time
     *
     * @param lastModifyTime the value for uc_corp_info.last_modify_time
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setLastModifyTime(Long lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }
}