package com.keqiaokeji.tezizai.common.dbmapper.uc.domain;

public class UcUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.user_id
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.username
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.password
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.email
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.mobile_phone
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.telephone
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.qq_num
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private String qqNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.sex
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.age
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.headPhoto
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private String headphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.birthday
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private Long birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.card_address
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private String cardAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.current_address
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private String currentAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.status
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.record_status
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private String recordStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.create_user_id
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.create_time
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.last_modify_user_id
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private String lastModifyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.last_modify_time
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    private Long lastModifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.user_id
     *
     * @return the value of uc_user_info.user_id
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.user_id
     *
     * @param userId the value for uc_user_info.user_id
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.username
     *
     * @return the value of uc_user_info.username
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.username
     *
     * @param username the value for uc_user_info.username
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.password
     *
     * @return the value of uc_user_info.password
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.password
     *
     * @param password the value for uc_user_info.password
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.email
     *
     * @return the value of uc_user_info.email
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.email
     *
     * @param email the value for uc_user_info.email
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.mobile_phone
     *
     * @return the value of uc_user_info.mobile_phone
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.mobile_phone
     *
     * @param mobilePhone the value for uc_user_info.mobile_phone
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.telephone
     *
     * @return the value of uc_user_info.telephone
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.telephone
     *
     * @param telephone the value for uc_user_info.telephone
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.qq_num
     *
     * @return the value of uc_user_info.qq_num
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public String getQqNum() {
        return qqNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.qq_num
     *
     * @param qqNum the value for uc_user_info.qq_num
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setQqNum(String qqNum) {
        this.qqNum = qqNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.sex
     *
     * @return the value of uc_user_info.sex
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.sex
     *
     * @param sex the value for uc_user_info.sex
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.age
     *
     * @return the value of uc_user_info.age
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.age
     *
     * @param age the value for uc_user_info.age
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.headPhoto
     *
     * @return the value of uc_user_info.headPhoto
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public String getHeadphoto() {
        return headphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.headPhoto
     *
     * @param headphoto the value for uc_user_info.headPhoto
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setHeadphoto(String headphoto) {
        this.headphoto = headphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.birthday
     *
     * @return the value of uc_user_info.birthday
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public Long getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.birthday
     *
     * @param birthday the value for uc_user_info.birthday
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.card_address
     *
     * @return the value of uc_user_info.card_address
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public String getCardAddress() {
        return cardAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.card_address
     *
     * @param cardAddress the value for uc_user_info.card_address
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setCardAddress(String cardAddress) {
        this.cardAddress = cardAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.current_address
     *
     * @return the value of uc_user_info.current_address
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public String getCurrentAddress() {
        return currentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.current_address
     *
     * @param currentAddress the value for uc_user_info.current_address
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setCurrentAddress(String currentAddress) {
        this.currentAddress = currentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.status
     *
     * @return the value of uc_user_info.status
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.status
     *
     * @param status the value for uc_user_info.status
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.record_status
     *
     * @return the value of uc_user_info.record_status
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public String getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.record_status
     *
     * @param recordStatus the value for uc_user_info.record_status
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setRecordStatus(String recordStatus) {
        this.recordStatus = recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.create_user_id
     *
     * @return the value of uc_user_info.create_user_id
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.create_user_id
     *
     * @param createUserId the value for uc_user_info.create_user_id
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.create_time
     *
     * @return the value of uc_user_info.create_time
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.create_time
     *
     * @param createTime the value for uc_user_info.create_time
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.last_modify_user_id
     *
     * @return the value of uc_user_info.last_modify_user_id
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public String getLastModifyUserId() {
        return lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.last_modify_user_id
     *
     * @param lastModifyUserId the value for uc_user_info.last_modify_user_id
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setLastModifyUserId(String lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.last_modify_time
     *
     * @return the value of uc_user_info.last_modify_time
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public Long getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.last_modify_time
     *
     * @param lastModifyTime the value for uc_user_info.last_modify_time
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    public void setLastModifyTime(Long lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }
}