package com.shk.baseframe.api.uc.domain;

import java.util.Date;

public class UcUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.user_id
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.username
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.password
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.email
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.mobile_phone
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.telephone
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.qq_num
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    private String qqNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.sex
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.age
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.brithday
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    private Date brithday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.card_address
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    private String cardAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.current_address
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    private String currentAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.state
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.record_state
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    private String recordState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.create_user_id
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.create_time
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.last_modify_user_id
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    private String lastModifyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_info.last_modify_time
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    private Date lastModifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.user_id
     *
     * @return the value of uc_user_info.user_id
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.user_id
     *
     * @param userId the value for uc_user_info.user_id
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.username
     *
     * @return the value of uc_user_info.username
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.username
     *
     * @param username the value for uc_user_info.username
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.password
     *
     * @return the value of uc_user_info.password
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.password
     *
     * @param password the value for uc_user_info.password
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.email
     *
     * @return the value of uc_user_info.email
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.email
     *
     * @param email the value for uc_user_info.email
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.mobile_phone
     *
     * @return the value of uc_user_info.mobile_phone
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.mobile_phone
     *
     * @param mobilePhone the value for uc_user_info.mobile_phone
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.telephone
     *
     * @return the value of uc_user_info.telephone
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.telephone
     *
     * @param telephone the value for uc_user_info.telephone
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.qq_num
     *
     * @return the value of uc_user_info.qq_num
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public String getQqNum() {
        return qqNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.qq_num
     *
     * @param qqNum the value for uc_user_info.qq_num
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public void setQqNum(String qqNum) {
        this.qqNum = qqNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.sex
     *
     * @return the value of uc_user_info.sex
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.sex
     *
     * @param sex the value for uc_user_info.sex
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.age
     *
     * @return the value of uc_user_info.age
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.age
     *
     * @param age the value for uc_user_info.age
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.brithday
     *
     * @return the value of uc_user_info.brithday
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public Date getBrithday() {
        return brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.brithday
     *
     * @param brithday the value for uc_user_info.brithday
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public void setBrithday(Date brithday) {
        this.brithday = brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.card_address
     *
     * @return the value of uc_user_info.card_address
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public String getCardAddress() {
        return cardAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.card_address
     *
     * @param cardAddress the value for uc_user_info.card_address
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public void setCardAddress(String cardAddress) {
        this.cardAddress = cardAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.current_address
     *
     * @return the value of uc_user_info.current_address
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public String getCurrentAddress() {
        return currentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.current_address
     *
     * @param currentAddress the value for uc_user_info.current_address
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public void setCurrentAddress(String currentAddress) {
        this.currentAddress = currentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.state
     *
     * @return the value of uc_user_info.state
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.state
     *
     * @param state the value for uc_user_info.state
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.record_state
     *
     * @return the value of uc_user_info.record_state
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public String getRecordState() {
        return recordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.record_state
     *
     * @param recordState the value for uc_user_info.record_state
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public void setRecordState(String recordState) {
        this.recordState = recordState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.create_user_id
     *
     * @return the value of uc_user_info.create_user_id
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.create_user_id
     *
     * @param createUserId the value for uc_user_info.create_user_id
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.create_time
     *
     * @return the value of uc_user_info.create_time
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.create_time
     *
     * @param createTime the value for uc_user_info.create_time
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.last_modify_user_id
     *
     * @return the value of uc_user_info.last_modify_user_id
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public String getLastModifyUserId() {
        return lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.last_modify_user_id
     *
     * @param lastModifyUserId the value for uc_user_info.last_modify_user_id
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public void setLastModifyUserId(String lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_info.last_modify_time
     *
     * @return the value of uc_user_info.last_modify_time
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_info.last_modify_time
     *
     * @param lastModifyTime the value for uc_user_info.last_modify_time
     *
     * @mbggenerated Fri May 09 14:36:06 CST 2014
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }
}