package com.keqiaokeji.tezizai.common.dbmapper.uc.mapper;

import com.keqiaokeji.tezizai.common.dbmapper.uc.domain.UcCorpInfo;
import com.keqiaokeji.tezizai.common.dbmapper.uc.domain.UcCorpInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UcCorpInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_corp_info
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    int countByExample(UcCorpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_corp_info
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    int deleteByExample(UcCorpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_corp_info
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    int deleteByPrimaryKey(String corpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_corp_info
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    int insert(UcCorpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_corp_info
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    int insertSelective(UcCorpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_corp_info
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    List<UcCorpInfo> selectByExample(UcCorpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_corp_info
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    UcCorpInfo selectByPrimaryKey(String corpId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_corp_info
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    int updateByExampleSelective(@Param("record") UcCorpInfo record, @Param("example") UcCorpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_corp_info
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    int updateByExample(@Param("record") UcCorpInfo record, @Param("example") UcCorpInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_corp_info
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    int updateByPrimaryKeySelective(UcCorpInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_corp_info
     *
     * @mbggenerated Tue Jun 03 15:27:32 CST 2014
     */
    int updateByPrimaryKey(UcCorpInfo record);
}